"""
Centralized enemy configurations.
Define enemy templates that can be referenced in level files.
"""

# Enemy type definitions - use these as templates in level configs
ENEMY_TYPES = {
    # Baby level enemies
    "baby_erzieherin": {
        "name": "Baby Erzieherin (Boss)",
        "image": "enemies/baby-erzieherin.png",
        "speed": 1,
        "patrol_range": 150,
        "size_multiplier": 4,
        "health": 50,
        "damage": 5,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 10,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
        "spawn_on_death": None,
    },
    "teddybear": {
        "name": "Teddybear",
        "image": "enemies/teddybear.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 3,
        "health": 30,
        "damage": 5,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 10,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    # Trancefloor enemies
    "trance_totem": {
        "name": "Trance Totem",
        "image": "enemies/trance-totem.png",
        "speed": 2,
        "patrol_range": 100,
        "size_multiplier": 4,
        "health": 15,
        "damage": 5,
        "shoot_range": 5,
        "chase_range": 10,
        "melee_damage": 2,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Suffi guck! Das erste Totem!",
        "shoot_cooldown": 60,
    },
    "trance_jesus": {
        "name": "Trance Jesus",
        "image": "enemies/trance-jesus.png",
        "speed": 3,
        "patrol_range": 100,
        "size_multiplier": 4,
        "health": 20,
        "damage": 5,
        "shoot_range": 30,
        "chase_range": 20,
        "melee_damage": 4,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Sweet Baby Jesus dieses Acid war aber keine Microdose",
        "shoot_cooldown": 60,
    },
    "trance_hippie": {
        "name": "Trance Hippie",
        "image": "enemies/trance-hippie.png",
        "speed": 1,
        "patrol_range": 30,
        "size_multiplier": 4,
        "health": 20,
        "damage": 2,
        "shoot_range": 30,
        "chase_range": 5,
        "melee_damage": 2,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Durch die Röhre ab in den Hippie Wald!",
        "shoot_cooldown": 60,
    },
    "trance_okf": {
        "name": "OKF Guardian (Boss)",
        "image": "enemies/trance-okf.png",
        "speed": 2,
        "patrol_range": 300,
        "size_multiplier": 4,
        "health": 100,
        "damage": 20,
        "shoot_range": 100,
        "chase_range": 100,
        "melee_damage": 25,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "OKF Macker verpiss dich!",
        "shoot_cooldown": 30,
    },
    "dj_booth": {
        "name": "DJ Booth (Final Boss)",
        "image": "enemies/trancefloor/dj-booth.png",
        "speed": 0,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 40,
        "damage": 1,
        "shoot_range": 100,
        "chase_range": 0,
        "melee_damage": 50,
        "can_throw_explosives": False,
        "can_summon_minions": True,
        "encounter_message": "Jetzt nur noch länger durchhalten als die DJ..",
        "shoot_cooldown": 10,
    },
    # Graffiti level enemies
    "trump": {
        "name": "Trump",
        "image": "trump.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 1,
        "health": 2,
        "damage": 1,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "trance_shroom": {
        "name": "Trance Shroom",
        "image": "enemies/trance-mushroom.png",
        "speed": 2,
        "patrol_range": 50,
        "size_multiplier": 2,
        "health": 10,
        "damage": 1,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Du süßer kleiner Pilz",
        "shoot_cooldown": 60,
    },
    # Hospital level enemies
    "patient": {
        "name": "Patient",
        "image": "enemies/hospital/patient_2.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 2,
        "damage": 2,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "patient_follower": {
        "name": "Patient_follower",
        "image": "enemies/hospital/patient_2.png",
        "speed": 2.5,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 1000,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
        "no_clip": True,  # Can walk through blocks
    },
    "patient_f": {
        "name": "Patient_f",
        "image": "enemies/hospital/patient_f.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 2,
        "damage": 2,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "patient_f_follower": {
        "name": "Patient_f_follower",
        "image": "enemies/hospital/patient_f.png",
        "speed": 2,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 1000,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
        "no_clip": True,  # Can walk through blocks
    },
    "patient_f_young": {
        "name": "Patient_f_young",
        "image": "enemies/hospital/patient_young_f.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 2,
        "damage": 20,
        "shoot_range": 10,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "patient_f_young_follower": {
        "name": "Patient_f_young_follower",
        "image": "enemies/hospital/patient_young_f.png",
        "speed": 1.5,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 1000,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
        "no_clip": True,  # Can walk through blocks
    },
    "doctor_f": {
        "name": "Doctor_f",
        "image": "enemies/hospital/Oberärztin.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 2,
        "damage": 2,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "doctor_f_follower": {
        "name": "Doctor_f_follower",
        "image": "enemies/hospital/Oberärztin.png",
        "speed": 2,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 1000,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
        "no_clip": True,  # Can walk through blocks
    },
    "doctor": {
        "name": "Doctor",
        "image": "enemies/hospital/doctor.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 10,
        "damage": 50,
        "shoot_range": 10,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "doctor_follower": {
        "name": "Doctor_follower",
        "image": "enemies/hospital/doctor.png",
        "speed": 1,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 1000,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
        "no_clip": True,  # Can walk through blocks
    },
    "doctor_old": {
        "name": "Doctor_old",
        "image": "enemies/hospital/Oberarzt.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 30,
        "damage": 20,
        "shoot_range": 10,
        "chase_range": 10,
        "melee_damage": 1,
        "can_throw_explosives": True,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "doctor_old_follower": {
        "name": "Doctor_old_follower",
        "image": "enemies/hospital/Oberarzt.png",
        "speed": 1,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 1000,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
        "no_clip": True,  # Can walk through blocks
    },
    "house": {
        "name": "house",
        "image": "enemies/hospital/house.png",
        "speed": 1.5,
        "patrol_range": 10,
        "size_multiplier": 5,
        "health": 100,
        "damage": 30,
        "shoot_range": 0,
        "chase_range": 10,
        "melee_damage": 30,
        "can_throw_explosives": True,
        "explosive_image": "stock.png",  # Custom explosive image for this enemy
        "explosive_size": 40,  # Size of stock explosive (default is 15)
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "jonas": {
        "name": "jonas",
        "image": "enemies/hospital/jonas.png",
        "speed": 0,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 0,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Da bist du ja endlich! \n Da hinten ist der Bus!",
        "shoot_cooldown": 60,
    },
    "paul": {
        "name": "paul",
        "image": "enemies/hospital/paul.png",
        "speed": 0,
        "patrol_range": 0,
        "size_multiplier": 4,
        "health": 99999,
        "damage": 0,
        "shoot_range": 0,
        "chase_range": 0,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    # Generic enemies for other levels
    "basic_enemy": {
        "name": "Basic Enemy",
        "image": "enemies/basic.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 2,
        "health": 10,
        "damage": 5,
        "shoot_range": 5,
        "chase_range": 10,
        "melee_damage": 5,
        "can_throw_explosives": True,
        "can_summon_minions": False,
        "encounter_message": None,
        "shoot_cooldown": 60,
    },
    "druide": {
        "name": "Druide",
        "image": "enemies/trancefloor/druide.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 10,
        "damage": 5,
        "shoot_range": 5,
        "chase_range": 50,
        "melee_damage": 20,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Crazy Druiden Kutte wo hast du die denn her?",
        "shoot_cooldown": 60,
        "spawn_on_death": {
            "type": "presslufthanna",
        },
    },
    "presslufthanna": {
        "name": "Presslufthanna",
        "image": "enemies/trancefloor/plh.png",
        "speed": 1,
        "patrol_range": 50,
        "size_multiplier": 4,
        "health": 100,
        "damage": 10,
        "shoot_range": 5,
        "chase_range": 50,
        "melee_damage": 30,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Es ist PLH!",
        "shoot_cooldown": 20,
    },
    "tightill": {
        "name": "Tightill",
        "image": "enemies/tightill.png",
        "speed": 1,
        "patrol_range": 200,
        "size_multiplier": 4,
        "health": 40,
        "damage": 5,
        "shoot_range": 5,
        "chase_range": 200,
        "melee_damage": 20,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Das ist T-t-t-t-t-t-tightill!",
        "shoot_cooldown": 20,
    },
    "robodog": {
        "name": "Robodog",
        "image": "enemies/graffiti/robodog.png",
        "speed": 3,
        "patrol_range": 200,
        "size_multiplier": 2,
        "health": 40,
        "damage": 5,
        "shoot_range": 0,
        "chase_range": 200,
        "melee_damage": 20,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Bye Bye!",
        "shoot_cooldown": 20,
    },
    "drone": {
        "name": "Surveillance Drone",
        "image": "enemies/graffiti/drone.png",
        "speed": 2,
        "patrol_range": 200,
        "size_multiplier": 2,
        "health": 10,
        "damage": 1,
        "shoot_range": 100,
        "chase_range": 200,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Bye Bye!",
        "shoot_cooldown": 30,
    },
    "police": {
        "name": "Police Officer",
        "image": "enemies/graffiti/police.png",
        "speed": 2,
        "patrol_range": 200,
        "size_multiplier": 4,
        "health": 10,
        "damage": 1,
        "shoot_range": 100,
        "chase_range": 200,
        "melee_damage": 0,
        "can_throw_explosives": False,
        "can_summon_minions": False,
        "encounter_message": "Halt stehenbleiben!",
        "shoot_cooldown": 30,
    },
}


def get_enemy_config(enemy_type, **overrides):
    """
    Get enemy configuration with optional overrides.

    Args:
        enemy_type: Type of enemy from ENEMY_TYPES
        **overrides: Any parameters to override (e.g., x, y, health, speed)

    Returns:
        Dictionary with complete enemy configuration

    Example:
        get_enemy_config('trance_totem', x=100, y=50, health=30)
    """
    if enemy_type not in ENEMY_TYPES:
        raise ValueError(
            f"Unknown enemy type: {enemy_type}. Available types: {list(ENEMY_TYPES.keys())}"
        )

    # Start with the template
    config = ENEMY_TYPES[enemy_type].copy()

    # Apply overrides
    config.update(overrides)

    return config
